### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by dady8889**
Made some fixes to annoying bugs that I've found. Please, tell me what do you think.
Also bumped the version to 0.3 to differentiate the versions.

* Fixed drag and drop errors
* Fixed inaccurate opening of files/folders
* Fixed interaction with "Dash to Dock" extension by delaying the load (i know, this is a bad fix)

### CODE REVIEW

**Comment by Ste74** [comment]
Thank you to work on it :+1:

**Comment by Ste74** [comment]
Tomorrow pushing the pkg in AUR and in Manjaro repo
You want granted Access here? If yes no problem.. Tell me..

**Comment by dady8889** [comment]
@Ste74 It would help a lot if you could give the access, thank you

**Comment by Ste74** [comment]
Ok now i m with my smartphone.. Tomorrow grant Access for you :)
More confortable work with my pc ;)

**Pull request merged**
